# Generated by Django 4.0.6 on 2022-08-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='destination_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
