# Generated by Django 4.0.6 on 2022-08-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destinations_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
