# Generated by Django 4.0.6 on 2022-08-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destinations_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='slug',
        ),
    ]
