# Generated by Django 4.0.6 on 2022-08-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_destinations_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='slug',
        ),
        migrations.AddField(
            model_name='destinations',
            name='destination_price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
