# Generated by Django 4.0.6 on 2022-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_remove_destinations_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.CharField(max_length=50)),
                ('new_price', models.CharField(max_length=50)),
            ],
        ),
    ]
