# Generated by Django 4.0.6 on 2022-08-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_remove_manali_day1_remove_manali_itineraryhead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manali',
            name='daycontent1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manali',
            name='daycontent2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manali',
            name='daycontent3',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manali',
            name='daycontent4',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manali',
            name='dayno2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manali',
            name='dayno3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manali',
            name='dayno4',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manali',
            name='itineraryhead1',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manali',
            name='itineraryhead2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manali',
            name='itineraryhead3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manali',
            name='itineraryhead4',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
