# Generated by Django 4.0.6 on 2022-08-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_alter_manali_daycontent1_alter_manali_daycontent2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
