# Generated by Django 4.0.6 on 2022-08-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0014_delete_manali_destinations_daycontent1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
