# Generated by Django 4.0.6 on 2022-08-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0015_destinations_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
