# Generated by Django 4.0.6 on 2022-08-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0016_alter_destinations_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='category',
            new_name='batch1',
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='inner_title',
            new_name='batch2',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='destination_title',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='inner_details',
        ),
        migrations.AddField(
            model_name='destinations',
            name='batch3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='batch4',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='batch5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='batch6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='batch7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode1',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode1_price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode2_price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode3_price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode4_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode5_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
