# Generated by Django 4.0.6 on 2022-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0018_remove_destinations_inner_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='inclusions10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='inclusions6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='inclusions7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='inclusions8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='inclusions9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
