# Generated by Django 4.0.6 on 2022-09-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0021_alter_destinations_daycontent10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='mode6',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='mode6_price',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
