# Generated by Django 4.0.6 on 2022-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0022_destinations_mode6_destinations_mode6_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='daycontent1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent4',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
