# Generated by Django 4.0.6 on 2022-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0023_alter_destinations_daycontent1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='daycontent1',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent10',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent2',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent3',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent4',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent5',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent6',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent7',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent8',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='daycontent9',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='expect1',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='expect2',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
