# Generated by Django 4.0.6 on 2022-08-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_provider', models.CharField(max_length=500)),
            ],
        ),
    ]
