# Generated by Django 4.0.6 on 2022-08-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bikingtours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('destination_title', models.CharField(max_length=100)),
                ('inner_video', models.CharField(max_length=500)),
                ('inner_details', models.CharField(max_length=100)),
                ('inner_title', models.CharField(max_length=50)),
                ('destination_price', models.CharField(max_length=50)),
            ],
        ),
    ]
