# Generated by Django 4.0.6 on 2022-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_backpacktrip_daycontent1_backpacktrip_daycontent10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadtours',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
