# Generated by Django 4.0.6 on 2022-08-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_roadtours_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadtours',
            name='id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='main_image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
