# Generated by Django 4.0.6 on 2022-08-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_roadtours_id_alter_roadtours_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadtours',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
