# Generated by Django 4.0.6 on 2022-08-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_populartours_recenttours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populartours',
            name='inner_details',
        ),
        migrations.RemoveField(
            model_name='populartours',
            name='inner_title',
        ),
        migrations.RemoveField(
            model_name='populartours',
            name='inner_video',
        ),
    ]
