# Generated by Django 4.0.6 on 2022-08-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_recenttours_inner_details_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leh',
            new_name='lehtrip',
        ),
    ]
