# Generated by Django 4.0.6 on 2022-08-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_roadtours_mode_roadtours_mode_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadtours',
            old_name='mode',
            new_name='mode1',
        ),
        migrations.RenameField(
            model_name='roadtours',
            old_name='mode_price',
            new_name='mode1_price',
        ),
        migrations.AddField(
            model_name='roadtours',
            name='mode2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadtours',
            name='mode2_price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadtours',
            name='mode3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadtours',
            name='mode3_price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
