# Generated by Django 4.0.6 on 2022-08-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_roadtours_batch1_roadtours_batch2_roadtours_batch3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadtours',
            name='mode1',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='mode1_price',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='mode2',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='mode2_price',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='mode3',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='mode3_price',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='mode4',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='mode4_price',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='mode5',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roadtours',
            name='mode5_price',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
