# Generated by Django 4.0.6 on 2022-08-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_backpack_inner_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenttours',
            name='relatedit1',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recenttours',
            name='relatedit2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recenttours',
            name='relatedprice1',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recenttours',
            name='relatedprice2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recenttours',
            name='relatedtour1',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recenttours',
            name='relatedtour2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
