# Generated by Django 4.0.6 on 2022-08-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_recenttours_relatedit1_recenttours_relatedit2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenttours',
            name='reltourimg1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='recenttours',
            name='reltourimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recenttours',
            name='relatedit1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recenttours',
            name='relatedit2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recenttours',
            name='relatedprice1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recenttours',
            name='relatedprice2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recenttours',
            name='relatedtour1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recenttours',
            name='relatedtour2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
