# Generated by Django 4.0.6 on 2022-09-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_inner_title_trekking_batch1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lehtrip',
            name='relatedit1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lehtrip',
            name='relatedit2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lehtrip',
            name='relatedprice1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lehtrip',
            name='relatedprice2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lehtrip',
            name='relatedtour1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lehtrip',
            name='relatedtour2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lehtrip',
            name='reltourimg1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lehtrip',
            name='reltourimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
