# Generated by Django 4.0.6 on 2022-08-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveenquiry',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
